on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://dariusxdragoi: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@github.com:ftos-tests/darius-testA.git"
          source_branch: "main"
          destination_repo: "https://dariusxdragoi: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@github.com:ftos-tests/darius-testB.git"
          destination_branch: "main"
