on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:ftos-tests/darius-testA"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:ftos-tests/darius-testB"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}          
  git-sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:ftos-tests/darius-testA"
          source_branch: "refs/releases/*"
          destination_repo: "git@github.com:ftos-tests/darius-testB"
          destination_branch: "refs/releases/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
