name: Sync Repos

on:
  push
    
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: get-repos
        run: |
          curl -i -u dariusxdragoi:acceces https://api.github.com/orgs/ftos-forks/repos > /home/runner/work/darius-test/darius-test/repos
          cat /home/runner/work/darius-test/darius-test/repos
