name: Sync Repos

on:
  push
    
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: get-repos
        run: |
          echo "Hello" > /home/runner/work/darius-test/darius-test/repos
          cat /home/runner/work/darius-test/darius-test/repos
