name: Sync Repos

on:
  push
    
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: get-repos
        run: cat "curl -i -u dariusxdragoi:acceces https://api.github.com/repos/ftos-forks/setup-node"
        
